In [1]:
import pandas as pd

In [2]:
result = pd.read_csv("X:/ProgramFiles/JetBrains/PycharmProjects/NBA-predictor/resources/researches/elo_parameters.tsv", sep="\t")

In [3]:
result

     Basic ELO  k0  lambda  accuracy  precision  recall      f1  roc_auc
0         1500  20     NaN    0.6305     0.6437  0.6930  0.6649   0.6858
1          500   2     0.2    0.6209     0.6288  0.7058  0.6631   0.6640
2          500   2     0.4    0.6220     0.6314  0.7007  0.6623   0.6686
3          500   2     0.6    0.6259     0.6366  0.6962  0.6630   0.6758
4          500   2     0.8    0.6301     0.6420  0.6959  0.6656   0.6820
..         ...  ..     ...       ...        ...     ...     ...      ...
195        600  20     1.0    0.6032     0.6133  0.6898  0.6483   0.6416
196        600  20     1.2    0.5953     0.6053  0.6908  0.6440   0.6304
197        600  20     1.4    0.5905     0.5997  0.6943  0.6427   0.6258
198        600  20     1.6    0.5967     0.6041  0.7047  0.6492   0.6256
199        600  20     1.8    0.5970     0.6060  0.6962  0.6468   0.6235

[200 rows x 8 columns]