In [2]:
import pandas as pd

In [3]:
result = pd.read_csv("X:/ProgramFiles/JetBrains/PycharmProjects/NBA-predictor/resources/researches/elo_parameters.tsv", sep="\t")

In [9]:
result

      Basic ELO  k0  lambda  accuracy  precision  recall      f1  roc_auc
0          1500  20     NaN    0.6305     0.6437  0.6930  0.6649   0.6858
1           500   2     0.2    0.6209     0.6288  0.7058  0.6631   0.6640
2           500   2     0.4    0.6220     0.6314  0.7007  0.6623   0.6686
3           500   2     0.6    0.6257     0.6365  0.6962  0.6630   0.6758
4           500   2     0.8    0.6301     0.6420  0.6965  0.6656   0.6820
...         ...  ..     ...       ...        ...     ...     ...      ...
1049       1700  18     1.0    0.6052     0.6159  0.6863  0.6481   0.6463
1050       1700  18     1.2    0.5960     0.6060  0.6889  0.6440   0.6324
1051       1700  18     1.4    0.5960     0.6042  0.6986  0.6469   0.6282
1052       1700  18     1.6    0.5913     0.5994  0.7028  0.6459   0.6256
1053       1700  18     1.8    0.5982     0.6063  0.7015  0.6491   0.6305

[1054 rows x 8 columns]