In [1]:
import pandas as pd

In [2]:
svm_configurations = pd.read_csv('X:/ProgramFiles/JetBrains/PycharmProjects/NBA-predictor/resources/models/hyper-tuning/svm.tsv', sep='\t')

svm_configurations.sort_values(by='accuracy', ascending=False)

          C   kernel degree  probability  accuracy
618    1.00     poly      2         True   0.94508
619    1.00     poly      2        False   0.94508
458   10.00     poly      1         True   0.94054
459   10.00     poly      1        False   0.94054
779    0.10     poly      3        False   0.94049
...     ...      ...    ...          ...       ...
710    1.00  sigmoid      -         True   0.47267
703    1.00  sigmoid      -        False   0.47267
702    1.00  sigmoid      -         True   0.47267
695    1.00  sigmoid      -        False   0.47267
1063   0.01  sigmoid      -        False   0.47267

[1064 rows x 5 columns]

In [3]:
mlp_configurations = pd.read_csv('X:/ProgramFiles/JetBrains/PycharmProjects/NBA-predictor/resources/models/hyper-tuning/neural-network.tsv', sep='\t')

mlp_configurations.sort_values(by='accuracy', ascending=False)

,layers,activation,solver,alpha,learning_rate,learning_rate_init,accuracy
0,hidden_layer_sizes,activation,solver,alpha,learning_rate,learning_rate_init,accuracy
16487,[128],relu,sgd,0.01,adaptive,0.0001,0.9037
14407,[96],relu,sgd,1e-05,adaptive,0.0001,0.89921
16327,[96],relu,sgd,0.01,adaptive,0.0001,0.8972
15207,[128],relu,sgd,0.0001,adaptive,0.0001,0.89456
...,...,...,...,...,...,...,...
19419,"[64, 64, 64, 64]",relu,sgd,1000.0,invscaling,0.01,0.43562
7327,"[64, 64, 64, 64, 64, 64, 64, 64]",tanh,sgd,1e-05,invscaling,0.0001,0.43314
12865,"[32, 32, 32, 32, 32]",tanh,sgd,10000.0,adaptive,0.1,0.42733
14475,"[96, 96, 96, 96, 96]",relu,sgd,1e-05,invscaling,0.01,0.42489
6576,[64],logistic,adam,100000.0,invscaling,0.0001,0.41771

In [4]:
lgr_configurations = pd.read_csv('X:/ProgramFiles/JetBrains/PycharmProjects/NBA-predictor/resources/models/hyper-tuning/logistic-regression.tsv', sep='\t')

lgr_configurations.sort_values(by='accuracy', ascending=False)

         C regularization           solver  accuracy
5     1.00             l1        liblinear   0.98393
1   100.00             l1        liblinear   0.98166
3    10.00             l1        liblinear   0.98161
4     1.00             l1             saga   0.98161
10  100.00             l2            lbfgs   0.97939
11  100.00             l2        liblinear   0.97939
12  100.00             l2        newton-cg   0.97939
13  100.00             l2  newton-cholesky   0.97939
14  100.00             l2              sag   0.97711
0   100.00             l1             saga   0.97479
16   10.00             l2            lbfgs   0.97479
21   10.00             l2             saga   0.97479
19   10.00             l2  newton-cholesky   0.97479
18   10.00             l2        newton-cg   0.97479
17   10.00             l2        liblinear   0.97479
20   10.00             l2              sag   0.97479
2    10.00             l1             saga   0.97479
15  100.00             l2             saga   0.97252
22    1.00             l2            lbfgs   0.96327
24    1.00             l2        newton-cg   0.96327
25    1.00             l2  newton-cholesky   0.96327
26    1.00             l2              sag   0.96327
27    1.00             l2             saga   0.96327
23    1.00             l2        liblinear   0.96094
29    0.10             l2        liblinear   0.94952
33    0.10             l2             saga   0.94952
32    0.10             l2              sag   0.94952
31    0.10             l2  newton-cholesky   0.94952
30    0.10             l2        newton-cg   0.94952
28    0.10             l2            lbfgs   0.94952
7     0.10             l1        liblinear   0.92669
6     0.10             l1             saga   0.92442
35    0.01             l2        liblinear   0.91977
34    0.01             l2            lbfgs   0.91755
36    0.01             l2        newton-cg   0.91755
37    0.01             l2  newton-cholesky   0.91755
38    0.01             l2              sag   0.91755
39    0.01             l2             saga   0.91755
9     0.01             l1        liblinear   0.48827
8     0.01             l1             saga   0.47717

In [5]:
rf_configurations = pd.read_csv('X:/ProgramFiles/JetBrains/PycharmProjects/NBA-predictor/resources/models/hyper-tuning/random-forest.tsv', sep='\t')

rf_configurations.sort_values(by='accuracy', ascending=False)

,n_estimators,max_features,max_depth,min_samples_split,min_samples_leaf,bagging,accuracy
14755,20,14,60.0,4,4,True,0.97711
43646,30,6,60.0,4,2,False,0.97711
19828,50,12,80.0,3,1,True,0.97711
57266,30,8,NaN,3,1,False,0.97711
9148,50,12,40.0,2,4,True,0.97711
...,...,...,...,...,...,...,...
19050,1,2,80.0,3,4,True,0.75460
21720,1,2,90.0,4,3,True,0.74979
2790,1,2,20.0,2,3,True,0.74556
8235,1,2,40.0,2,4,True,0.74556
8145,1,2,40.0,2,2,True,0.72262

In [6]:
gnb_configurations = pd.read_csv('X:/ProgramFiles/JetBrains/PycharmProjects/NBA-predictor/resources/models/hyper-tuning/gaussian-naive-bayes.tsv', sep='\t')

gnb_configurations.sort_values(by='accuracy', ascending=False)

   var_smoothing  accuracy
0   1.000000e-11   0.95402
1   1.000000e-10   0.95402
2   1.000000e-09   0.95402
3   1.000000e-08   0.95402