In [1]:
import pandas as pd
from pandas import DataFrame

from utils import generateSeasons

from sklearn.preprocessing import *

In [2]:
path_to_resources = "X:/ProgramFiles/JetBrains/PycharmProjects/NBA-predictor/resources"

In [3]:
game_logs: pd.DataFrame = pd.concat([pd.read_csv(f"{path_to_resources}/game-logs/season_{season}.tsv", sep='\t') for season in generateSeasons(2018,2023)])

advanced_statistics: pd.DataFrame = pd.concat(
    [
        pd.read_csv(f"{path_to_resources}/per-game-statistics/season_{season}.tsv", sep='\t') for season in generateSeasons(2018,2023)
    ]
)

In [4]:
game_logs.shape

(14118, 27)

In [5]:
advanced_statistics.shape

(14118, 39)

In [6]:
game_logs.rename(columns={"Game_ID": "GAME_ID", "Team_ID": "TEAM_ID"}, inplace=True)

In [7]:
advanced_statistics.columns

Index(['GAME_ID', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CITY',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS',
       'PLUS_MINUS', 'OFF_RATING', 'DEF_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'PACE', 'PIE'],
      dtype='object')

In [8]:
chosen_columns = [
    'GAME_ID', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CITY',
       'OFF_RATING', 'DEF_RATING', 'TS_PCT', 'PACE'
]

In [9]:
dataset = game_logs.merge(advanced_statistics[chosen_columns], on=["GAME_ID", "TEAM_ID"], how='left')

In [10]:
dataset.shape

(14118, 34)

In [11]:
dataset.head(10)

,TEAM_ID,GAME_ID,GAME_DATE,MATCHUP,WL,W,L,W_PCT,MIN,FGM,...,TOV,PF,PTS,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,OFF_RATING,DEF_RATING,TS_PCT,PACE
0,1610612737,21801220,"APR 10, 2019",ATL vs. IND,L,29,53,0.354,240,43,...,17,25,134,Hawks,ATL,Atlanta,122.9,125.0,0.560,108.50
1,1610612737,21801202,"APR 07, 2019",ATL @ MIL,L,29,52,0.358,240,40,...,11,28,107,Hawks,ATL,Atlanta,99.1,106.5,0.494,108.00
2,1610612737,21801181,"APR 05, 2019",ATL @ ORL,L,29,51,0.363,240,41,...,14,21,113,Hawks,ATL,Atlanta,102.7,134.2,0.525,110.50
3,1610612737,21801168,"APR 03, 2019",ATL vs. PHI,W,29,50,0.367,240,48,...,11,26,130,Hawks,ATL,Atlanta,126.2,118.4,0.623,103.00
4,1610612737,21801162,"APR 02, 2019",ATL @ SAS,L,28,50,0.359,240,43,...,11,18,111,Hawks,ATL,Atlanta,108.8,113.6,0.540,102.50
5,1610612737,21801145,"MAR 31, 2019",ATL vs. MIL,W,28,49,0.364,265,52,...,9,13,136,Hawks,ATL,Atlanta,114.3,115.4,0.542,106.87
6,1610612737,21801131,"MAR 29, 2019",ATL vs. POR,L,27,49,0.355,240,38,...,10,22,98,Hawks,ATL,Atlanta,98.0,116.8,0.489,100.50
7,1610612737,21801113,"MAR 26, 2019",ATL @ NOP,W,27,48,0.360,240,44,...,16,26,130,Hawks,ATL,Atlanta,115.0,105.3,0.599,113.50
8,1610612737,21801088,"MAR 23, 2019",ATL vs. PHI,W,26,48,0.351,240,49,...,12,25,129,Hawks,ATL,Atlanta,117.3,116.5,0.560,109.50
9,1610612737,21801076,"MAR 21, 2019",ATL vs. UTA,W,25,48,0.342,240,41,...,16,23,117,Hawks,ATL,Atlanta,110.4,108.6,0.602,105.50

In [12]:
dataset.columns

Index(['TEAM_ID', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'W', 'L', 'W_PCT',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'OFF_RATING',
       'DEF_RATING', 'TS_PCT', 'PACE'],
      dtype='object')

In [13]:
dataset.dtypes

TEAM_ID                int64
GAME_ID                int64
GAME_DATE             object
MATCHUP               object
WL                    object
W                      int64
L                      int64
W_PCT                float64
MIN                    int64
FGM                    int64
FGA                    int64
FG_PCT               float64
FG3M                   int64
FG3A                   int64
FG3_PCT              float64
FTM                    int64
FTA                    int64
FT_PCT               float64
OREB                   int64
DREB                   int64
REB                    int64
AST                    int64
STL                    int64
BLK                    int64
TOV                    int64
PF                     int64
PTS                    int64
TEAM_NAME             object
TEAM_ABBREVIATION     object
TEAM_CITY             object
OFF_RATING           float64
DEF_RATING           float64
TS_PCT               float64
PACE                 float64
dtype: object

In [14]:
columns_to_check = [
    'W_PCT', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS',  'OFF_RATING', 'DEF_RATING', 'TS_PCT', 'PACE'
]

valid_gameIds = pd.read_csv(f'{path_to_resources}/datasets/data.csv', sep='\t')["GAME_ID"].tolist()

dataset = dataset[dataset["GAME_ID"].isin(valid_gameIds)]


dataset[columns_to_check].describe().round(decimals=3).astype(object).transpose()

            count     mean     std    min     25%     50%    75%    max
W_PCT       968.0    0.498   0.165  0.122   0.383   0.554  0.605  0.803
FGM         968.0   41.802   5.436   26.0    38.0    42.0   46.0   65.0
FGA         968.0   88.451   7.179   70.0    83.0    88.0   93.0  114.0
FG_PCT      968.0    0.473   0.056  0.316   0.437   0.474  0.512  0.663
FG3M        968.0   12.887   3.822    2.0    10.0    13.0   15.0   27.0
FG3A        968.0   35.399   6.172   20.0    31.0    35.0   39.0   63.0
FG3_PCT     968.0    0.363   0.083  0.069   0.308   0.364  0.414  0.636
FTM         968.0   15.724   5.545    0.0    12.0    16.0   19.0   40.0
FTA         968.0   20.059   6.542    0.0    15.0    20.0   24.0   45.0
FT_PCT      968.0    0.781    0.11    0.0   0.714   0.792  0.857    1.0
OREB        968.0    10.34   3.736    0.0     8.0    10.0   13.0   25.0
DREB        968.0   33.149   5.438   17.0   29.75    33.0   37.0   55.0
REB         968.0   43.489   6.608   25.0    39.0    43.0   48.0   74.0
AST         968.0   26.701   5.112   12.0    23.0    27.0   30.0   43.0
STL         968.0     7.63    2.82    1.0     6.0     7.0    9.0   17.0
BLK         968.0    5.077   2.676    0.0     3.0     5.0    7.0   16.0
TOV         968.0    12.79   3.687    3.0    10.0    13.0   15.0   27.0
PF          968.0   17.571    3.98    4.0    15.0    17.0   20.0   34.0
PTS         968.0  112.215  12.578   73.0   104.0   112.0  121.0  157.0
OFF_RATING  968.0  113.572  11.784   77.0  105.45  114.05  121.3  155.9
DEF_RATING  968.0  113.572  11.784   77.0  105.45  114.05  121.3  155.9
TS_PCT      968.0    0.578   0.063  0.389   0.534   0.578  0.622  0.789
PACE        968.0   98.314   4.673   83.5    95.0    98.5  101.0  114.0

In [15]:
nulls_summary = pd.DataFrame(dataset.isnull().any(), columns=['Nulls'])
nulls_summary['Num_of_nulls [qty]'] = pd.DataFrame(dataset.isnull().sum())
nulls_summary['Num_of_nulls [%]'] = round((dataset.isnull().mean()*100),2)
nulls_summary

                   Nulls  Num_of_nulls [qty]  Num_of_nulls [%]
TEAM_ID            False                   0               0.0
GAME_ID            False                   0               0.0
GAME_DATE          False                   0               0.0
MATCHUP            False                   0               0.0
WL                 False                   0               0.0
W                  False                   0               0.0
L                  False                   0               0.0
W_PCT              False                   0               0.0
MIN                False                   0               0.0
FGM                False                   0               0.0
FGA                False                   0               0.0
FG_PCT             False                   0               0.0
FG3M               False                   0               0.0
FG3A               False                   0               0.0
FG3_PCT            False                   0               0.0
FTM                False                   0               0.0
FTA                False                   0               0.0
FT_PCT             False                   0               0.0
OREB               False                   0               0.0
DREB               False                   0               0.0
REB                False                   0               0.0
AST                False                   0               0.0
STL                False                   0               0.0
BLK                False                   0               0.0
TOV                False                   0               0.0
PF                 False                   0               0.0
PTS                False                   0               0.0
TEAM_NAME          False                   0               0.0
TEAM_ABBREVIATION  False                   0               0.0
TEAM_CITY          False                   0               0.0
OFF_RATING         False                   0               0.0
DEF_RATING         False                   0               0.0
TS_PCT             False                   0               0.0
PACE               False                   0               0.0

In [16]:
scaler = StandardScaler()

In [17]:
elo_ratings = pd.concat([pd.read_csv(f'{path_to_resources}/elo-ratings/season_{season}.tsv', sep='\t') for season in generateSeasons(2018,2023)])

elo_ratings_teams_x = elo_ratings[["Game_ID", "Team_ID_x", "ELO_x"]]
elo_ratings_teams_x.rename(columns={"Game_ID": "GAME_ID", "Team_ID_x": "TEAM_ID", "ELO_x": "ELO"}, inplace=True)

elo_ratings_teams_y = elo_ratings[["Game_ID", "Team_ID_y", "ELO_y"]]
elo_ratings_teams_y.rename(columns={"Game_ID": "GAME_ID", "Team_ID_y": "TEAM_ID", "ELO_y": "ELO"}, inplace=True)

elo_ratings_simplified = pd.concat([elo_ratings_teams_x, elo_ratings_teams_y], ignore_index=True)

elo_ratings_simplified

C:\Users\Mateusz\AppData\Local\Temp\ipykernel_23284\3421663110.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elo_ratings_teams_x.rename(columns={"Game_ID": "GAME_ID", "Team_ID_x": "TEAM_ID", "ELO_x": "ELO"}, inplace=True)
C:\Users\Mateusz\AppData\Local\Temp\ipykernel_23284\3421663110.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elo_ratings_teams_y.rename(columns={"Game_ID": "GAME_ID", "Team_ID_y": "TEAM_ID", "ELO_y": "ELO"}, inplace=True)

        GAME_ID     TEAM_ID     ELO
0      21800001  1610612738  1300.0
1      21800002  1610612744  1300.0
2      21800003  1610612749  1300.0
3      21800004  1610612751  1300.0
4      21800005  1610612754  1300.0
...         ...         ...     ...
14113  22301196  1610612760  1604.0
14114  22301197  1610612765  1196.0
14115  22301198  1610612762  1299.0
14116  22301199  1610612746  1521.0
14117  22301200  1610612758  1499.0

[14118 rows x 3 columns]

In [18]:
dataset = dataset.merge(elo_ratings_simplified, on=["GAME_ID", "TEAM_ID"], how='left')
dataset.describe().round(decimals=3).astype(object).transpose()

,count,mean,std,min,25%,50%,75%,max
TEAM_ID,968.0,1610612751.554,8.735,1610612737.0,1610612744.0,1610612752.0,1610612759.0,1610612766.0
GAME_ID,968.0,22300947.262,150.135,22300583.0,22300818.75,22300949.5,22301078.25,22301200.0
W,968.0,32.675,12.035,6.0,24.0,34.0,42.0,64.0
L,968.0,32.849,11.956,11.0,24.0,31.0,40.0,68.0
W_PCT,968.0,0.498,0.165,0.122,0.383,0.554,0.605,0.803
MIN,968.0,241.343,6.492,240.0,240.0,240.0,240.0,290.0
FGM,968.0,41.802,5.436,26.0,38.0,42.0,46.0,65.0
FGA,968.0,88.451,7.179,70.0,83.0,88.0,93.0,114.0
FG_PCT,968.0,0.473,0.056,0.316,0.437,0.474,0.512,0.663
FG3M,968.0,12.887,3.822,2.0,10.0,13.0,15.0,27.0
FG3A,968.0,35.399,6.172,20.0,31.0,35.0,39.0,63.0
FG3_PCT,968.0,0.363,0.083,0.069,0.308,0.364,0.414,0.636
FTM,968.0,15.724,5.545,0.0,12.0,16.0,19.0,40.0
FTA,968.0,20.059,6.542,0.0,15.0,20.0,24.0,45.0
FT_PCT,968.0,0.781,0.11,0.0,0.714,0.792,0.857,1.0
OREB,968.0,10.34,3.736,0.0,8.0,10.0,13.0,25.0
DREB,968.0,33.149,5.438,17.0,29.75,33.0,37.0,55.0
REB,968.0,43.489,6.608,25.0,39.0,43.0,48.0,74.0
AST,968.0,26.701,5.112,12.0,23.0,27.0,30.0,43.0
STL,968.0,7.63,2.82,1.0,6.0,7.0,9.0,17.0
BLK,968.0,5.077,2.676,0.0,3.0,5.0,7.0,16.0
TOV,968.0,12.79,3.687,3.0,10.0,13.0,15.0,27.0
PF,968.0,17.571,3.98,4.0,15.0,17.0,20.0,34.0
PTS,968.0,112.215,12.578,73.0,104.0,112.0,121.0,157.0
OFF_RATING,968.0,113.572,11.784,77.0,105.45,114.05,121.3,155.9
DEF_RATING,968.0,113.572,11.784,77.0,105.45,114.05,121.3,155.9
TS_PCT,968.0,0.578,0.063,0.389,0.534,0.578,0.622,0.789
PACE,968.0,98.314,4.673,83.5,95.0,98.5,101.0,114.0
ELO,968.0,1453.818,146.238,1139.0,1365.0,1487.0,1557.0,1777.0

In [19]:
normalized_array = scaler.fit_transform(dataset[columns_to_check + ["ELO"]])

normalized_dataset = DataFrame(normalized_array, columns=[columns_to_check + ["ELO"]])
normalized_dataset.describe().round(decimals=3).astype(object).transpose()

            count mean    std    min    25%    50%    75%    max
W_PCT       968.0  0.0  1.001 -2.283 -0.702  0.334  0.647  1.848
FGM         968.0  0.0  1.001 -2.909   -0.7  0.037  0.773   4.27
FGA         968.0  0.0  1.001 -2.572  -0.76 -0.063  0.634  3.561
FG_PCT      968.0  0.0  1.001  -2.83 -0.655   0.01  0.693  3.408
FG3M        968.0 -0.0  1.001  -2.85 -0.756  0.029  0.553  3.694
FG3A        968.0  0.0  1.001 -2.496 -0.713 -0.065  0.584  4.474
FG3_PCT     968.0  0.0  1.001 -3.544 -0.663  0.013  0.616  3.292
FTM         968.0 -0.0  1.001 -2.837 -0.672   0.05  0.591   4.38
FTA         968.0  0.0  1.001 -3.068 -0.774 -0.009  0.603  3.814
FT_PCT      968.0 -0.0  1.001 -7.134 -0.616  0.096   0.69  1.995
OREB        968.0 -0.0  1.001 -2.769 -0.627 -0.091  0.712  3.926
DREB        968.0  0.0  1.001 -2.971 -0.625 -0.027  0.709   4.02
REB         968.0 -0.0  1.001 -2.799  -0.68 -0.074  0.683  4.619
AST         968.0  0.0  1.001 -2.877 -0.724  0.058  0.646   3.19
STL         968.0 -0.0  1.001 -2.352 -0.578 -0.224  0.486  3.324
BLK         968.0 -0.0  1.001 -1.899 -0.777 -0.029  0.719  4.084
TOV         968.0 -0.0  1.001 -2.656 -0.757  0.057    0.6  3.856
PF          968.0 -0.0  1.001 -3.412 -0.646 -0.144  0.611   4.13
PTS         968.0  0.0  1.001 -3.119 -0.653 -0.017  0.699  3.563
OFF_RATING  968.0 -0.0  1.001 -3.105  -0.69  0.041  0.656  3.594
DEF_RATING  968.0 -0.0  1.001 -3.105  -0.69  0.041  0.656  3.594
TS_PCT      968.0 -0.0  1.001  -3.01 -0.701 -0.001    0.7   3.36
PACE        968.0 -0.0  1.001 -3.172  -0.71   0.04  0.575  3.359
ELO         968.0  0.0  1.001 -2.154 -0.608  0.227  0.706  2.211